// AUTO MAINTAINED FILE: DO NOT CHANGE

export const HOME_COUNTER_PLUS_ONE = 'HOME_COUNTER_PLUS_ONE';
export const HOME_COUNTER_MINUS_ONE = 'HOME_COUNTER_MINUS_ONE';
export const HOME_RESET_COUNTER = 'HOME_RESET_COUNTER';
export const HOME_FETCH_REDDIT_REACTJS_LIST_BEGIN = 'HOME_FETCH_REDDIT_REACTJS_LIST_BEGIN';
export const HOME_FETCH_REDDIT_REACTJS_LIST_SUCCESS = 'HOME_FETCH_REDDIT_REACTJS_LIST_SUCCESS';
export const HOME_FETCH_REDDIT_REACTJS_LIST_FAILURE = 'HOME_FETCH_REDDIT_REACTJS_LIST_FAILURE';
export const HOME_FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR = 'HOME_FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR';
export const HOME_USER_LOGGED_IN_SUCESSFULY = 'HOME_USER_LOGGED_IN_SUCESSFULY';
export const HOME_USER_LOGGED_OUT_SUCESSFULY = 'HOME_USER_LOGGED_OUT_SUCESSFULY';
export const HOME_LOAD_RESTAURANTS_BY_TYPE_BEGIN = 'HOME_LOAD_RESTAURANTS_BY_TYPE_BEGIN';
export const HOME_LOAD_RESTAURANTS_BY_TYPE_SUCCESS = 'HOME_LOAD_RESTAURANTS_BY_TYPE_SUCCESS';
export const HOME_LOAD_RESTAURANTS_BY_TYPE_FAILURE = 'HOME_LOAD_RESTAURANTS_BY_TYPE_FAILURE';
export const HOME_LOAD_RESTAURANTS_BY_TYPE_DISMISS_ERROR = 'HOME_LOAD_RESTAURANTS_BY_TYPE_DISMISS_ERROR';
export const HOME_LOAD_ALL_RESTAURANTS_BY_COUSINE_BEGIN = 'HOME_LOAD_ALL_RESTAURANTS_BY_COUSINE_BEGIN';
export const HOME_LOAD_ALL_RESTAURANTS_BY_COUSINE_SUCCESS = 'HOME_LOAD_ALL_RESTAURANTS_BY_COUSINE_SUCCESS';
export const HOME_LOAD_ALL_RESTAURANTS_BY_COUSINE_FAILURE = 'HOME_LOAD_ALL_RESTAURANTS_BY_COUSINE_FAILURE';
export const HOME_LOAD_ALL_RESTAURANTS_BY_COUSINE_DISMISS_ERROR = 'HOME_LOAD_ALL_RESTAURANTS_BY_COUSINE_DISMISS_ERROR';
export const HOME_LOAD_ALL_DISHES_BY_RESTAURANT_BEGIN = 'HOME_LOAD_ALL_DISHES_BY_RESTAURANT_BEGIN';
export const HOME_LOAD_ALL_DISHES_BY_RESTAURANT_SUCCESS = 'HOME_LOAD_ALL_DISHES_BY_RESTAURANT_SUCCESS';
export const HOME_LOAD_ALL_DISHES_BY_RESTAURANT_FAILURE = 'HOME_LOAD_ALL_DISHES_BY_RESTAURANT_FAILURE';
export const HOME_LOAD_ALL_DISHES_BY_RESTAURANT_DISMISS_ERROR = 'HOME_LOAD_ALL_DISHES_BY_RESTAURANT_DISMISS_ERROR';
export const HOME_ADD_PRODUCT_TO_CART = 'HOME_ADD_PRODUCT_TO_CART';
export const HOME_REMOVE_PRODUCT_FROM_CART = 'HOME_REMOVE_PRODUCT_FROM_CART';
