export const STUDENT_LOAD_STUDENT_LIST_BEGIN = 'STUDENT_LOAD_STUDENT_LIST_BEGIN';
export const STUDENT_LOAD_STUDENT_LIST_SUCCESS = 'STUDENT_LOAD_STUDENT_LIST_SUCCESS';
export const STUDENT_LOAD_STUDENT_LIST_FAILURE = 'STUDENT_LOAD_STUDENT_LIST_FAILURE';
export const STUDENT_LOAD_STUDENT_LIST_DISMISS_ERROR = 'STUDENT_LOAD_STUDENT_LIST_DISMISS_ERROR';
