export const STUDENT_LOAD_STUDENT_LIST_BEGIN = 'STUDENT_LOAD_STUDENT_LIST_BEGIN';
export const STUDENT_LOAD_STUDENT_LIST_SUCCESS = 'STUDENT_LOAD_STUDENT_LIST_SUCCESS';
export const STUDENT_LOAD_STUDENT_LIST_FAILURE = 'STUDENT_LOAD_STUDENT_LIST_FAILURE';
export const STUDENT_LOAD_STUDENT_LIST_DISMISS_ERROR = 'STUDENT_LOAD_STUDENT_LIST_DISMISS_ERROR';
export const STUDENT_SHOW_MODAL_NEW_STUDENT = 'STUDENT_SHOW_MODAL_NEW_STUDENT';
export const STUDENT_CLOSE_MODAL_NEW_STUDENT = 'STUDENT_CLOSE_MODAL_NEW_STUDENT';
